# AutoML is the Future (embrace it don't run away)  

After repeated fails against AutoML-based techniques I have decided to succumb.  

Here is a guide on how to use AutoML.

**DISCLAIMER: NOT WELL FORMATED!**

In [24]:
# !pip install "autogluon.tabular[all]" --extra-index-url https://download.pytorch.org/whl/cpu
# !pip install autoviz --upgrade

## AutoViz - Easy data visualisation

We will use the salary dataset that killed me during the selection training camp, located at `https://drive.google.com/file/d/10Kct0vldQfTgz7zncIUk_ZC3He3aA6xh/view?usp=sharing` (train) and `https://drive.google.com/file/d/11eZvKmY3ULXMviulJvtH91v0KfTHyCk1/view?usp=sharing` (test).

In [5]:
!pip install gdown

Requirement already satisfied: gdown in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from gdown) (4.13.4)
Requirement already satisfied: filelock in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from gdown) (3.18.0)
Requirement already satisfied: requests[socks] in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from beautifulsoup4->gdown) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from beautifulsoup4->gdown) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from requests[socks]->gdown) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from requests[socks]->gdown) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from requests[socks]->gdown) (2025.4.26)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages (from requests[socks]->gdown) (1.7.1)

In [8]:
import gdown
gdown.download("https://drive.google.com/uc?id=10Kct0vldQfTgz7zncIUk_ZC3He3aA6xh")
gdown.download("https://drive.google.com/uc?id=11eZvKmY3ULXMviulJvtH91v0KfTHyCk1")

Downloading...
From: https://drive.google.com/uc?id=10Kct0vldQfTgz7zncIUk_ZC3He3aA6xh
To: /home/walnit/Documents/NOAI/IOAI 2025/ML/ml_trainset.csv
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 186k/186k [00:00<00:00, 16.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=11eZvKmY3ULXMviulJvtH91v0KfTHyCk1
To: /home/walnit/Documents/NOAI/IOAI 2025/ML/ml_testset.csv
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18.0k/18.0k [00:00<00:00, 1.41MB/s]

'ml_testset.csv'

In [24]:
import pandas as pd

data = pd.read_csv("ml_trainset.csv")
data.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary_currency,employee_residence,remote_ratio,company_location,company_size,salary_in_usd
0,0,2023,SE,FT,Principal Data Scientist,EUR,ES,100,ES,L,85847
1,1,2023,MI,CT,ML Engineer,USD,US,100,US,S,30000
2,2,2023,MI,CT,ML Engineer,USD,US,100,US,S,25500
3,3,2023,SE,FT,Data Scientist,USD,CA,100,CA,M,175000
4,4,2023,SE,FT,Data Scientist,USD,CA,100,CA,M,120000

This data is so hard to read. Let's use AutoViz.

In [25]:
from autoviz import AutoViz_Class

AV = AutoViz_Class()

In [3]:
dft = AV.AutoViz(
    "", # empty filename, library is a bit cooked
    dfte=data,
    depVar="salary_in_usd",
    verbose=1, # dont save too much stuff to disk,
    chart_format="server",
)

Shape of your Data Set loaded: (3379, 11)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  1
    Number of String-Categorical Columns =  7
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  1
    Number of ID Columns =  1
    Number of Columns to Delete =  0
    10 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['Unnamed: 0']

################ Regression problem #####################

scatterplots can be found in URL below:
Launching server at http://localhost:38105

distplots can be found in URL below:
Launching server at http://localhost:36213
distplots can be found in URL below:
Launching server at http://localhost:38761

kde_plots can be found in URL below:
Launching server at http://localhost:37891

violinplots can be found in URL below:
Launching server at http://localhost:37595

timeseries_plots can be found in URL below:
Launching server at http://localhost:41907

cat_var_plots can be found in URL below:
Launching server at http://localhost:43623
Time to run AutoViz (in seconds) = 7

WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='fa3f7621-2f96-410a-9db2-4b03a4527c7f', ...)
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='93dc108a-c7c5-4545-876e-45a04b399ca8', ...)

From the plots, you can get a rough gauge of which variables are useful and which are not. Useful if you're doing manual data cleaning, but not so useful if you're using AutoGluon.  

However, we can also do some basic scaling and feature selection. First, lets automatically find data quality issues.

In [6]:
from autoviz import data_cleaning_suggestions

data_cleaning_suggestions(data)
print("") # remove double print

    All variables classified into correct types.

Looks scary to fix, but luckily, we have FixDQ.

In [26]:
from autoviz import FixDQ

fixdq = FixDQ()

We can use Jupyter's autocomplete to see all the features it offers. We can also quickly, and automatically, fix the problems.

In [27]:
data = data.drop(["Unnamed: 0"], axis=1)
rare_cats = fixdq.group_rare_categories(data[["job_title", "salary_currency", "employee_residence", "company_location"]])
data.loc[:, ["job_title", "salary_currency", "employee_residence", "company_location"]] = rare_cats
data.loc[:, ['work_year', 'remote_ratio']] = data[['work_year', 'remote_ratio']].astype(str)
old_feats = ['work_year', 'experience_level', 'employment_type', 'job_title', 'salary_currency', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']

categorical_feats = ['employment_type', 'job_title', 'salary_currency', 'employee_residence', 'company_location']
ordinal_feats = ['work_year', 'experience_level', 'remote_ratio', 'company_size']
data = pd.concat([data, pd.get_dummies(data[categorical_feats])], axis=1)
data = data.drop(categorical_feats, axis=1)
data.loc[:, "experience_level"] = pd.Categorical(data["experience_level"], ["EN", "MI", "SE", "EX"], ordered=True).codes
data.loc[:, "work_year"] = pd.Categorical(data["work_year"], ["2020", "2021", "2022", "2023"], ordered=True).codes
data.loc[:, "remote_ratio"] = pd.Categorical(data["remote_ratio"], ["0", "50", "100"], ordered=True).codes
data.loc[:, "company_size"] = pd.Categorical(data["company_size"], ["S", "M", "L"], ordered=True).codes
data.loc[:, "salary_in_usd"] = data["salary_in_usd"].clip(0, 295000)

data.head()

,work_year,experience_level,remote_ratio,company_size,salary_in_usd,employment_type_CT,employment_type_FL,employment_type_FT,employment_type_PT,job_title_Analytics Engineer,job_title_Applied Scientist,job_title_Data Analyst,job_title_Data Architect,job_title_Data Engineer,job_title_Data Science Manager,job_title_Data Scientist,job_title_Machine Learning Engineer,job_title_Rare,job_title_Research Engineer,job_title_Research Scientist,salary_currency_EUR,salary_currency_GBP,salary_currency_INR,salary_currency_Rare,salary_currency_USD,employee_residence_CA,employee_residence_DE,employee_residence_ES,employee_residence_FR,employee_residence_GB,employee_residence_IN,employee_residence_Rare,employee_residence_US,company_location_CA,company_location_DE,company_location_ES,company_location_GB,company_location_IN,company_location_Rare,company_location_US
0,3,2,2,2,85847,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
1,3,1,2,0,30000,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
2,3,1,2,0,25500,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
3,3,2,2,1,175000,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
4,3,2,2,1,120000,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3379 entries, 0 to 3378
Data columns (total 40 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   work_year                            3379 non-null   object
 1   experience_level                     3379 non-null   object
 2   remote_ratio                         3379 non-null   object
 3   company_size                         3379 non-null   object
 4   salary_in_usd                        3379 non-null   int64
 5   employment_type_CT                   3379 non-null   bool
 6   employment_type_FL                   3379 non-null   bool
 7   employment_type_FT                   3379 non-null   bool
 8   employment_type_PT                   3379 non-null   bool
 9   job_title_Analytics Engineer         3379 non-null   bool
 10  job_title_Applied Scientist          3379 non-null   bool
 11  job_title_Data Analyst               3379 non-null   bool
 12  job_title_Data Architect             3379 non-null   bool
 13  job_title_Data Engineer              3379 non-null   bool
 14  job_title_Data Science Manager       3379 non-null   bool
 15  job_title_Data Scientist             3379 non-null   bool
 16  job_title_Machine Learning Engineer  3379 non-null   bool
 17  job_title_Rare                       3379 non-null   bool
 18  job_title_Research Engineer          3379 non-null   bool
 19  job_title_Research Scientist         3379 non-null   bool
 20  salary_currency_EUR                  3379 non-null   bool
 21  salary_currency_GBP                  3379 non-null   bool
 22  salary_currency_INR                  3379 non-null   bool
 23  salary_currency_Rare                 3379 non-null   bool
 24  salary_currency_USD                  3379 non-null   bool
 25  employee_residence_CA                3379 non-null   bool
 26  employee_residence_DE                3379 non-null   bool
 27  employee_residence_ES                3379 non-null   bool
 28  employee_residence_FR                3379 non-null   bool
 29  employee_residence_GB                3379 non-null   bool
 30  employee_residence_IN                3379 non-null   bool
 31  employee_residence_Rare              3379 non-null   bool
 32  employee_residence_US                3379 non-null   bool
 33  company_location_CA                  3379 non-null   bool
 34  company_location_DE                  3379 non-null   bool
 35  company_location_ES                  3379 non-null   bool
 36  company_location_GB                  3379 non-null   bool
 37  company_location_IN                  3379 non-null   bool
 38  company_location_Rare                3379 non-null   bool
 39  company_location_US                  3379 non-null   bool
dtypes: bool(35), int64(1), object(4)
memory usage: 247.6+ KB

Okay, let's pass this into the AutoML model!

## AutoGluon - Automatic ML

In [28]:
from autogluon.tabular import TabularDataset, TabularPredictor

AutoGluon techniques are used with a `TabularDataset`, which is a subclass of a normal DataFrame.

In [29]:
ag_df = TabularDataset(data)
ag_df.head()

,work_year,experience_level,remote_ratio,company_size,salary_in_usd,employment_type_CT,employment_type_FL,employment_type_FT,employment_type_PT,job_title_Analytics Engineer,job_title_Applied Scientist,job_title_Data Analyst,job_title_Data Architect,job_title_Data Engineer,job_title_Data Science Manager,job_title_Data Scientist,job_title_Machine Learning Engineer,job_title_Rare,job_title_Research Engineer,job_title_Research Scientist,salary_currency_EUR,salary_currency_GBP,salary_currency_INR,salary_currency_Rare,salary_currency_USD,employee_residence_CA,employee_residence_DE,employee_residence_ES,employee_residence_FR,employee_residence_GB,employee_residence_IN,employee_residence_Rare,employee_residence_US,company_location_CA,company_location_DE,company_location_ES,company_location_GB,company_location_IN,company_location_Rare,company_location_US
0,3,2,2,2,85847,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
1,3,1,2,0,30000,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
2,3,1,2,0,25500,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
3,3,2,2,1,175000,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False
4,3,2,2,1,120000,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False

Training is simple.

In [30]:
predictor = TabularPredictor(label="salary_in_usd").fit(ag_df, presets="high", time_limit=300)

No path specified. Models will be saved in: "AutogluonModels/ag-20250625_160110"
Preset alias specified: 'high' maps to 'high_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.12.8
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu, 19 Jun 2025 14:41:19 +0000
CPU Count:          8
Memory Avail:       10.19 GB / 15.42 GB (66.1%)
Disk Space Avail:   34.79 GB / 224.81 GB (15.5%)
===================================================
Presets specified: ['high']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 75s of the 300s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2025-06-26 00:01:12,034	INFO worker.py:1843 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
		Context path: "/home/walnit/Documents/NOAI/IOAI 2025/ML/AutogluonModels/ag-20250625_160110/ds_sub_fit/sub_fit_ho"
(_dystack pid=45707) Running DyStack sub-fit ...
(_dystack pid=45707) Beginning AutoGluon training ... Time limit = 71s
(_dystack pid=45707) AutoGluon will save models to "/home/walnit/Documents/NOAI/IOAI 2025/ML/AutogluonModels/ag-20250625_160110/ds_sub_fit/sub_fit_ho"
(_dystack pid=45707) Train Data Rows:    3003
(_dystack pid=45707) Train Data Columns: 39
(_dystack pid=45707) Label Column:       salary_in_usd
(_dystack pid=45707) Problem Type:       regression
(_dystack pid=45707) Preprocessing data ...
(_dystack pid=45707) Using Feature Generators to preprocess the data ...
(_dystack pid=45707) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=45707) 	Available Memory:                    9820.47 MB
(_dystack pid=45707) 	Train Data (Original)  Memory Usage: 0.51 MB (0.0% of available memory)
(_dystack pid=45707) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=45707) 	Stage 1 Generators:
(_dystack pid=45707) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=45707) 			Note: Converting 35 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=45707) 	Stage 2 Generators:
(_dystack pid=45707) 		Fitting FillNaFeatureGenerator...
(_dystack pid=45707) 	Stage 3 Generators:
(_dystack pid=45707) 		Fitting IdentityFeatureGenerator...
(_dystack pid=45707) 		Fitting CategoryFeatureGenerator...
(_dystack pid=45707) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=45707) 	Stage 4 Generators:
(_dystack pid=45707) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=45707) 	Stage 5 Generators:
(_dystack pid=45707) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=45707) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=45707) 		('bool', [])   : 35 | ['employment_type_CT', 'employment_type_FL', 'employment_type_FT', 'employment_type_PT', 'job_title_Analytics Engineer', ...]
(_dystack pid=45707) 		('object', []) :  4 | ['work_year', 'experience_level', 'remote_ratio', 'company_size']
(_dystack pid=45707) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=45707) 		('category', [])  :  4 | ['work_year', 'experience_level', 'remote_ratio', 'company_size']
(_dystack pid=45707) 		('int', ['bool']) : 35 | ['employment_type_CT', 'employment_type_FL', 'employment_type_FT', 'employment_type_PT', 'job_title_Analytics Engineer', ...]
(_dystack pid=45707) 	0.6s = Fit runtime
(_dystack pid=45707) 	39 features in original data used to generate 39 features in processed data.
(_dystack pid=45707) 	Train Data (Processed) Memory Usage: 0.11 MB (0.0% of available memory)
(_dystack pid=45707) Data preprocessing and feature engineering runtime = 0.63s ...
(_dystack pid=45707) AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
(_dystack pid=45707) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=45707) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=45707) Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=45707) User-specified model hyperparameters to be fit:
(_dystack pid=45707) {
(_dystack pid=45707) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=45707) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=45707) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=45707) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=45707) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=45707) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=45707) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=45707) 	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
(_dystack pid=45707) }
(_dystack pid=45707) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=45707) Fitting 108 L1 models, fit_strategy="sequential" ...
(_dystack pid=45707) Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 47.18s of the 70.77s of remaining time.
(_dystack pid=45707) 	No valid features to train KNeighborsUnif_BAG_L1... Skipping this model.
(_dystack pid=45707) Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 47.11s of the 70.71s of remaining time.
(_dystack pid=45707) 	No valid features to train KNeighborsDist_BAG_L1... Skipping this model.
(_dystack pid=45707) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 47.02s of the 70.62s of remaining time.
(_dystack pid=45707) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.11%)
(_dystack pid=45707) 	-46454.2345	 = Validation score   (-root_mean_squared_error)
(_dystack pid=45707) 	5.23s	 = Training   runtime
(_dystack pid=45707) 	0.17s	 = Validation runtime
(_dystack pid=45707) Fitting model: LightGBM_BAG_L1 ... Training model for up to 35.32s of the 58.92s of remaining time.
(_dystack pid=45707) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.13%)
(_dystack pid=45707) 	-46662.8358	 = Validation score   (-root_mean_squared_error)
(_dystack pid=45707) 	4.37s	 = Training   runtime
(_dystack pid=45707) 	0.17s	 = Validation runtime
(_dystack pid=45707) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 25.26s of the 48.86s of remaining time.
(_dystack pid=45707) /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=45707)   warnings.warn(
(_dystack pid=45707) 	-47809.1441	 = Validation score   (-root_mean_squared_error)
(_dystack pid=45707) 	1.73s	 = Training   runtime
(_dystack pid=45707) 	0.32s	 = Validation runtime
(_dystack pid=45707) Fitting model: CatBoost_BAG_L1 ... Training model for up to 23.13s of the 46.73s of remaining time.
(_dystack pid=45707) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=4.56%)
(_dystack pid=45707) 	-46349.0127	 = Validation score   (-root_mean_squared_error)
(_dystack pid=45707) 	13.82s	 = Training   runtime
(_dystack pid=45707) 	0.1s	 = Validation runtime
(_dystack pid=45707) Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 3.90s of the 27.50s of remaining time.
(_dystack pid=45707) /home/walnit/Documents/NOAI/IOAI 2025/.env/lib/python3.12/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=45707)   warnings.warn(
(_dystack pid=45707) 	-47753.3418	 = Validation score   (-root_mean_squared_error)
(_dystack pid=45707) 	1.09s	 = Training   runtime
(_dystack pid=45707) 	0.26s	 = Validation runtime
(_dystack pid=45707) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 2.50s of the 26.10s of remaining time.
(_dystack pid=45707) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.02%)
(_ray_fit pid=47299) 	Ran out of time, stopping training early. (Stopping on epoch 5)
(_dystack pid=45707) 	-48467.2144	 = Validation score   (-root_mean_squared_error)
(_dystack pid=45707) 	10.18s	 = Training   runtime
(_dystack pid=45707) 	0.28s	 = Validation runtime
(_dystack pid=45707) Fitting model: WeightedEnsemble_L2 ... Training model for up to 70.79s of the 10.27s of remaining time.
(_dystack pid=45707) 	Ensemble Weights: {'CatBoost_BAG_L1': 0.542, 'LightGBMXT_BAG_L1': 0.417, 'NeuralNetFastAI_BAG_L1': 0.042}
(_dystack pid=45707) 	-46162.5664	 = Validation score   (-root_mean_squared_error)
(_dystack pid=45707) 	0.04s	 = Training   runtime
(_dystack pid=45707) 	0.0s	 = Validation runtime
(_dystack pid=45707) Fitting 106 L2 models, fit_strategy="sequential" ...
(_dystack pid=45707) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 10.21s of the 10.11s of remaining time.
(_dystack pid=45707) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.17%)

(_ray_fit pid=47622) [1000]	valid_set's rmse: 41075.5

(_ray_fit pid=47622) 	Ran out of time, early stopping on iteration 3920. Best iteration is:
(_ray_fit pid=47622) 	[3330]	valid_set's rmse: 39715.3
(_ray_fit pid=47302) 	Ran out of time, stopping training early. (Stopping on epoch 5) [repeated 7x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)

(_ray_fit pid=47618) [4000]	valid_set's rmse: 32776 [repeated 24x across cluster]

(_dystack pid=45707) 	-35547.0566	 = Validation score   (-root_mean_squared_error)
(_dystack pid=45707) 	13.45s	 = Training   runtime
(_dystack pid=45707) 	10.76s	 = Validation runtime
(_dystack pid=45707) Fitting model: WeightedEnsemble_L3 ... Training model for up to 70.79s of the -11.14s of remaining time.
(_dystack pid=45707) 	Ensemble Weights: {'LightGBMXT_BAG_L2': 0.895, 'CatBoost_BAG_L1': 0.105}
(_dystack pid=45707) 	-35377.6062	 = Validation score   (-root_mean_squared_error)
(_dystack pid=45707) 	0.04s	 = Training   runtime
(_dystack pid=45707) 	0.0s	 = Validation runtime
(_dystack pid=45707) AutoGluon training complete, total runtime = 82.61s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 32.5 rows/s (376 batch size)
(_dystack pid=45707) Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
(_dystack pid=45707) Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
(_dystack pid=45707) 	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
(_dystack pid=45707) 	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
(_dystack pid=45707) 	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
(_dystack pid=45707) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=45707) Fitting model: LightGBMXT_BAG_L1_FULL ...
(_dystack pid=45707) 	2.16s	 = Training   runtime
(_dystack pid=45707) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=45707) Fitting model: LightGBM_BAG_L1_FULL ...
(_ray_fit pid=47617) 	Ran out of time, early stopping on iteration 4014. Best iteration is: [repeated 7x across cluster]
(_ray_fit pid=47617) 	[3907]	valid_set's rmse: 34007.3 [repeated 7x across cluster]
(_dystack pid=45707) 	0.23s	 = Training   runtime
(_dystack pid=45707) Fitting model: RandomForestMSE_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=45707) 	1.73s	 = Training   runtime
(_dystack pid=45707) 	0.32s	 = Validation runtime
(_dystack pid=45707) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=45707) Fitting model: CatBoost_BAG_L1_FULL ...
(_dystack pid=45707) 	1.98s	 = Training   runtime
(_dystack pid=45707) Fitting model: ExtraTreesMSE_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=45707) 	1.09s	 = Training   runtime
(_dystack pid=45707) 	0.26s	 = Validation runtime
(_dystack pid=45707) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=45707) Fitting model: NeuralNetFastAI_BAG_L1_FULL ...
(_dystack pid=45707) 	Stopping at the best epoch learned earlier - 4.
(_dystack pid=45707) 	0.77s	 = Training   runtime
(_dystack pid=45707) Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=45707) 	Ensemble Weights: {'CatBoost_BAG_L1': 0.542, 'LightGBMXT_BAG_L1': 0.417, 'NeuralNetFastAI_BAG_L1': 0.042}
(_dystack pid=45707) 	0.04s	 = Training   runtime
(_dystack pid=45707) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=45707) Fitting model: LightGBMXT_BAG_L2_FULL ...
(_dystack pid=45707) 	3.54s	 = Training   runtime
(_dystack pid=45707) Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
(_dystack pid=45707) 	Ensemble Weights: {'LightGBMXT_BAG_L2': 0.895, 'CatBoost_BAG_L1': 0.105}
(_dystack pid=45707) 	0.04s	 = Training   runtime
(_dystack pid=45707) Updated best model to "WeightedEnsemble_L3_FULL" (Previously "WeightedEnsemble_L3"). AutoGluon will default to using "WeightedEnsemble_L3_FULL" for predict() and predict_proba().
(_dystack pid=45707) Refit complete, total runtime = 9.81s ... Best model: "WeightedEnsemble_L3_FULL"
(_dystack pid=45707) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/walnit/Documents/NOAI/IOAI 2025/ML/AutogluonModels/ag-20250625_160110/ds_sub_fit/sub_fit_ho")
(_dystack pid=45707) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
             model              score_holdout    score_val        eval_metric         pred_time_test  pred_time_val  fit_time   pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0     WeightedEnsemble_L2_FULL -40742.808340  -46162.566444  root_mean_squared_error     0.048338            NaN      4.950700         0.003226                      NaN             0.041815            2         True         7
1         CatBoost_BAG_L1_FULL -40867.043129  -46349.012656  root_mean_squared_error     0.007610            NaN      1.980623         0.007610                      NaN             1.980623            1         True         4
2       LightGBMXT_BAG_L1_FULL -41115.645757  -46454.234528  root_mean_squared_error     0.010963            NaN      2.156126         0.010963                      NaN             2.156126            1         True         1
3         LightGBM_BAG_L1_FULL -41382.830877  -46662.835809  root_mean_squared_error     0.008584            NaN      0.234797         0.008584                      NaN             0.234797            1         True         2
4  RandomForestMSE_BAG_L1_FULL -41992.301186  -47809.144078  root_mean_squared_error     0.125423       0.324087      1.725389         0.125423                 0.324087             1.725389            1         True         3
5    ExtraTreesMSE_BAG_L1_FULL -42006.439417  -47753.341773  root_mean_squared_error     0.107395       0.255339      1.091552         0.107395                 0.255339             1.091552            1         True         5
6  NeuralNetFastAI_BAG_L1_FULL -43314.885307  -48467.214351  root_mean_squared_error     0.026539            NaN      0.772136         0.026539                      NaN             0.772136            1         True         6
7     WeightedEnsemble_L3_FULL -44197.721388  -35377.606168  root_mean_squared_error     0.441739            NaN     11.543847         0.003469                      NaN             0.039173            3         True         9
8       LightGBMXT_BAG_L2_FULL -44951.761855  -35547.056572  root_mean_squared_error     0.438270            NaN     11.504674         0.151756                      NaN             3.544051            2         True         8
	0	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: True)
	98s	 = DyStack   runtime |	202s	 = Remaining runtime
Starting main fit with num_stack_levels=0.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=0)`
Beginning AutoGluon training ... Time limit = 202s
AutoGluon will save models to "/home/walnit/Documents/NOAI/IOAI 2025/ML/AutogluonModels/ag-20250625_160110"
Train Data Rows:    3379
Train Data Columns: 39
Label Column:       salary_in_usd
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9568.55 MB
	Train Data (Original)  Memory Usage: 0.58 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 35 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', [])   : 35 | ['employment_type_CT', 'employment_type_FL', 'employment_type_FT', 'employment_type_PT', 'job_title_Analytics Engineer', ...]
		('object', []) :  4 | ['work_year', 'experience_level', 'remote_ratio', 'company_size']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  4 | ['work_year', 'experience_level', 'remote_ratio', 'company_size']
		('int', ['bool']) : 35 | ['employment_type_CT', 'employment_type_FL', 'employment_type_FT', 'employment_type_PT', 'job_title_Analytics Engineer', ...]
	0.6s = Fit runtime
	39 features in original data used to generate 39 features in processed data.
	Train Data (Processed) Memory Usage: 0.13 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.63s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 108 L1 models, fit_strategy="sequential" ...
Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 200.89s of the 200.85s of remaining time.
	No valid features to train KNeighborsUnif_BAG_L1... Skipping this model.
Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 200.63s of the 200.59s of remaining time.
	No valid features to train KNeighborsDist_BAG_L1... Skipping this model.
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 200.41s of the 200.38s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.11%)
	-45883.736	 = Validation score   (-root_mean_squared_error)
	4.62s	 = Training   runtime
	0.27s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 188.32s of the 188.29s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.13%)
	-45986.4281	 = Validation score   (-root_mean_squared_error)
	5.23s	 = Training   runtime
	0.35s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 176.75s of the 176.71s of remaining time.
	-46954.4242	 = Validation score   (-root_mean_squared_error)
	1.58s	 = Training   runtime
	0.3s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 174.79s of the 174.76s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=4.28%)
	-45734.8088	 = Validation score   (-root_mean_squared_error)
	19.8s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 149.14s of the 149.10s of remaining time.
	-46899.9284	 = Validation score   (-root_mean_squared_error)
	1.14s	 = Training   runtime
	0.29s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 147.65s of the 147.61s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.01%)
	-45973.4817	 = Validation score   (-root_mean_squared_error)
	19.44s	 = Training   runtime
	0.35s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 122.20s of the 122.17s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.24%)
	-46064.618	 = Validation score   (-root_mean_squared_error)
	2.63s	 = Training   runtime
	0.16s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 112.43s of the 112.39s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.01%)
	-45877.8539	 = Validation score   (-root_mean_squared_error)
	42.24s	 = Training   runtime
	0.18s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 63.60s of the 63.56s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.44%)
	-46779.4363	 = Validation score   (-root_mean_squared_error)
	11.9s	 = Training   runtime
	0.56s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 45.00s of the 44.96s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=4.34%)
	-45638.7971	 = Validation score   (-root_mean_squared_error)
	4.49s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 34.33s of the 34.29s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=1, gpus=0, memory=0.01%)
	-46176.8219	 = Validation score   (-root_mean_squared_error)
	33.59s	 = Training   runtime
	0.22s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 200.89s of the -6.33s of remaining time.
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.28, 'CatBoost_BAG_L1': 0.2, 'NeuralNetFastAI_BAG_L1': 0.2, 'LightGBM_BAG_L1': 0.12, 'LightGBMXT_BAG_L1': 0.08, 'NeuralNetTorch_r79_BAG_L1': 0.08, 'CatBoost_r177_BAG_L1': 0.04}
	-45298.937	 = Validation score   (-root_mean_squared_error)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 207.96s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 266.2 rows/s (423 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1_FULL ...
	2.57s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	0.51s	 = Training   runtime
Fitting model: RandomForestMSE_BAG_L1_FULL | Skipping fit via cloning parent ...
	1.58s	 = Training   runtime
	0.3s	 = Validation runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost_BAG_L1_FULL ...
	2.82s	 = Training   runtime
Fitting model: ExtraTreesMSE_BAG_L1_FULL | Skipping fit via cloning parent ...
	1.14s	 = Training   runtime
	0.29s	 = Validation runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI_BAG_L1_FULL ...
	Stopping at the best epoch learned earlier - 18.
	3.58s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	0.65s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetTorch_BAG_L1_FULL ...
	6.0s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMLarge_BAG_L1_FULL ...
	1.34s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost_r177_BAG_L1_FULL ...
	0.27s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetTorch_r79_BAG_L1_FULL ...
	5.45s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.28, 'CatBoost_BAG_L1': 0.2, 'NeuralNetFastAI_BAG_L1': 0.2, 'LightGBM_BAG_L1': 0.12, 'LightGBMXT_BAG_L1': 0.08, 'NeuralNetTorch_r79_BAG_L1': 0.08, 'CatBoost_r177_BAG_L1': 0.04}
	0.06s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 24.14s ... Best model: "WeightedEnsemble_L2_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/walnit/Documents/NOAI/IOAI 2025/ML/AutogluonModels/ag-20250625_160110")

Fun fact, AutoGluon actually does not recommend us to do feature engineering, because it has in-built feature engineering. We can see what it does:

In [104]:
from autogluon.features.generators import AutoMLPipelineFeatureGenerator
auto_ml_feat_gen = AutoMLPipelineFeatureGenerator()
auto_ml_feat_gen.fit_transform(pd.read_csv("ml_testset.csv"))

Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9990.43 MB
	Train Data (Original)  Memory Usage: 0.14 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 3 | ['Unnamed: 0', 'work_year', 'remote_ratio']
		('object', []) : 7 | ['experience_level', 'employment_type', 'job_title', 'salary_currency', 'employee_residence', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 7 | ['experience_level', 'employment_type', 'job_title', 'salary_currency', 'employee_residence', ...]
		('int', [])      : 3 | ['Unnamed: 0', 'work_year', 'remote_ratio']
	0.1s = Fit runtime
	10 features in original data used to generate 10 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)

,Unnamed: 0,work_year,remote_ratio,experience_level,employment_type,job_title,salary_currency,employee_residence,company_location,company_size
0,3208,2022,100,2,1,5,1,5,NaN,1
1,1692,2023,0,3,1,10,4,8,6,1
2,2031,2022,100,2,1,5,4,8,6,1
3,1651,2023,0,3,1,10,4,8,6,1
4,107,2023,0,3,1,2,4,8,6,1
5,259,2023,100,3,1,7,4,8,6,1
6,3058,2022,0,3,1,13,4,8,6,1
7,1950,2022,0,2,1,5,4,8,6,1
8,367,2023,0,2,1,16,2,4,4,1
9,1013,2023,0,3,1,12,4,8,6,1
10,3558,2021,100,1,1,NaN,4,6,6,0
11,2030,2022,100,2,1,5,4,8,6,1
12,2814,2022,100,2,1,NaN,4,8,6,1
13,983,2023,0,0,1,NaN,4,8,6,1
14,3271,2022,100,3,1,10,4,8,6,1
15,1313,2023,100,3,1,10,4,8,6,1
16,2139,2022,0,3,1,10,1,2,2,1
17,116,2023,0,3,1,10,4,8,6,1
18,205,2023,0,2,1,7,4,8,6,1
19,3701,2021,100,3,1,16,4,3,6,2
20,576,2023,100,3,1,7,4,0,0,1
21,3118,2022,100,0,1,7,4,8,6,0
22,2302,2022,0,3,1,5,4,8,6,1
23,1299,2023,0,3,1,7,4,8,6,1
24,3281,2022,100,3,1,10,4,8,6,1
25,1327,2023,0,2,1,5,2,4,4,1
26,1915,2022,0,2,1,10,4,8,6,1
27,3200,2022,100,2,1,7,1,2,2,1
28,2337,2022,0,3,1,7,4,8,6,1
29,416,2023,100,3,1,10,4,8,6,1
30,2673,2022,100,3,1,10,4,8,6,1
31,1792,2023,0,3,1,10,4,0,0,1
32,2919,2022,0,3,1,2,4,8,6,1
33,2749,2022,100,3,1,10,4,8,6,1
34,413,2023,0,3,1,10,4,8,6,1
35,930,2023,100,3,1,10,4,8,6,1
36,646,2023,100,3,1,7,4,8,6,1
37,799,2023,100,3,1,6,4,8,6,1
38,1371,2023,0,2,1,7,4,8,6,1
39,2201,2022,0,3,1,7,4,8,6,1
40,2358,2022,100,0,1,10,NaN,NaN,NaN,1
41,1030,2023,100,3,1,5,4,8,6,1
42,1711,2023,0,2,1,12,2,4,4,1
43,967,2023,0,3,1,10,4,8,6,1
44,1111,2023,0,0,1,5,4,8,6,1
45,16,2023,0,3,1,NaN,4,8,6,1
46,2028,2022,0,0,1,10,4,8,6,1
47,213,2023,0,3,1,10,4,0,0,1
48,2266,2022,0,2,1,5,4,8,6,1
49,601,2023,100,0,1,7,4,8,6,1
50,914,2023,0,3,1,10,4,8,6,1
51,3232,2022,0,3,1,10,4,8,6,1
52,3398,2022,100,2,1,5,4,8,6,1
53,8,2023,0,3,1,10,4,0,0,1
54,3007,2022,0,2,1,7,2,4,4,1
55,704,2023,0,2,1,5,4,8,6,1
56,2851,2022,100,2,1,5,4,8,6,1
57,3718,2021,50,2,1,12,4,7,NaN,2
58,3128,2022,100,2,1,10,4,8,6,0
59,1521,2023,0,3,1,NaN,4,8,6,1
60,1949,2022,0,3,1,7,4,8,6,1
61,3438,2022,100,0,1,10,0,0,0,0
62,772,2023,0,3,1,7,2,4,4,1
63,492,2023,0,0,1,4,1,2,2,1
64,388,2023,100,2,1,10,4,8,6,1
65,3525,2021,50,3,1,NaN,0,0,0,0
66,167,2023,0,2,1,7,4,8,6,1
67,3669,2021,100,2,1,10,NaN,NaN,NaN,0
68,10,2023,0,3,1,10,4,8,6,1
69,353,2023,0,3,1,NaN,4,8,6,1
70,875,2023,0,2,1,7,4,8,6,1
71,642,2023,100,3,1,6,4,8,6,1
72,1419,2023,0,3,1,12,4,8,6,1
73,1199,2023,0,3,1,12,4,8,6,1
74,1725,2023,0,3,1,11,4,8,6,1
75,1006,2023,0,3,1,12,4,8,6,1
76,965,2023,0,3,1,10,1,2,2,1
77,486,2023,100,3,1,10,4,8,6,1
78,1514,2023,0,2,1,7,4,8,6,1
79,2495,2022,0,3,1,10,4,8,6,1
80,1844,2022,100,2,1,10,4,8,6,1
81,2564,2022,0,3,1,7,4,8,6,0
82,403,2023,0,3,1,5,4,8,6,1
83,1925,2022,0,1,1,7,4,8,6,1
84,2685,2022,100,3,NaN,5,4,8,6,1
85,2748,2022,100,3,1,10,4,8,6,1
86,2335,2021,50,2,0,NaN,4,NaN,NaN,1
87,2124,2022,0,3,1,7,4,8,6,1
88,785,2023,0,3,1,10,4,8,6,1
89,1136,2023,0,2,1,12,4,8,6,1
90,718,2023,0,3,1,16,4,8,6,1
91,3706,2020,50,2,1,10,1,3,3,2
92,3411,2022,100,1,1,7,4,8,6,1
93,2032,2021,50,2,1,5,3,6,5,0
94,650,2023,100,3,1,6,4,8,6,1
95,1530,2023,0,3,1,7,4,8,6,1
96,2355,2022,0,3,1,10,4,8,6,1
97,605,2023,100,2,1,5,4,8,6,1
98,778,2023,0,3,1,7,4,8,6,1
99,2239,2022,0,3,1,7,4,8,6,1
100,1370,2023,0,2,1,7,4,8,6,1
101,552,2023,0,2,1,7,4,8,6,1
102,532,2023,100,3,1,7,4,8,6,1
103,1249,2023,0,3,1,16,4,2,2,1
104,3469,2022,0,2,1,10,NaN,NaN,NaN,0
105,153,2023,100,2,1,7,4,8,6,1
106,3277,2022,100,3,1,5,4,8,6,1
107,332,2023,0,3,1,5,4,8,6,1
108,1411,2023,0,3,1,10,4,8,6,1
109,2784,2022,100,2,1,4,4,8,6,0
110,1148,2023,0,2,1,5,4,8,6,1
111,1043,2023,0,3,1,7,4,8,6,1
112,2397,2022,100,3,1,10,4,8,6,1
113,2832,2022,100,1,1,7,4,8,6,1
114,219,2023,0,2,1,0,NaN,NaN,NaN,1
115,2064,2022,100,3,1,5,4,8,6,1
116,534,2023,0,3,1,10,4,8,6,1
117,1491,2023,100,3,1,5,4,8,6,1
118,444,2023,0,3,1,5,4,8,6,1
119,547,2023,0,3,1,7,4,8,6,1
120,317,2023,100,3,1,8,4,8,6,1
121,2801,2022,100,3,1,7,4,8,6,1
122,791,2023,0,3,1,7,4,8,6,1
123,1618,2023,0,2,1,7,4,8,6,1
124,3003,2022,0,3,1,7,4,8,6,1
125,1132,2023,0,3,1,9,4,8,6,1
126,1855,2022,100,3,1,10,4,8,6,1
127,3142,2022,100,3,1,9,NaN,NaN,NaN,0
128,5,2023,0,3,1,3,4,8,6,0
129,151,2023,0,3,1,2,4,8,6,1
130,3751,2021,100,2,1,14,4,8,6,0
131,2729,2022,100,3,1,7,4,8,6,1
132,1685,2023,100,3,1,3,4,8,6,1
133,2938,2022,100,2,1,NaN,4,8,6,1
134,3236,2022,0,3,1,7,4,8,6,1
135,366,2023,0,2,1,5,4,8,6,1
136,1011,2023,0,3,1,10,4,8,6,1
137,1630,2023,100,0,1,10,4,6,6,1
138,2058,2022,0,3,1,5,4,8,6,1
139,247,2023,100,3,1,2,4,8,6,1
140,2922,2022,0,2,1,10,2,4,4,1
141,3610,2021,0,2,1,NaN,4,8,6,2
142,504,2023,0,3,1,7,4,8,6,1
143,1187,2023,100,3,1,12,4,8,6,1
144,1216,2023,100,3,1,7,4,8,6,1
145,3601,2021,50,3,1,NaN,0,0,0,1
146,2622,2022,0,3,1,10,4,8,6,1
147,2252,2022,0,3,1,10,4,8,6,1
148,1208,2023,100,0,1,15,4,4,4,1
149,385,2023,100,3,1,10,4,8,6,1
150,294,2023,0,3,1,3,4,8,6,0
151,1436,2023,100,3,1,10,4,8,6,1
152,855,2023,0,3,1,5,4,8,6,1
153,29,2023,0,3,1,NaN,4,0,0,1
154,1056,2023,0,3,1,5,4,8,6,1
155,3326,2022,0,3,1,10,4,8,6,1
156,3023,2022,100,2,1,5,3,6,5,2
157,3222,2022,100,2,1,7,2,4,4,1
158,3426,2022,100,0,1,10,3,6,5,1
159,631,2023,0,3,1,7,4,8,6,1
160,1290,2023,100,2,1,5,4,8,6,1
161,937,2023,100,0,1,5,4,8,6,1
162,2332,2022,100,3,1,16,4,8,6,1
163,3403,2022,0,2,1,10,2,4,4,1
164,1079,2023,0,3,1,7,4,8,6,1
165,2794,2022,100,3,1,6,4,8,6,0
166,2039,2022,0,3,1,NaN,4,8,6,1
167,2346,2022,0,3,1,12,4,8,6,1
168,1917,2022,50,0,1,NaN,4,NaN,NaN,2
169,3333,2022,100,3,1,5,4,8,6,1
170,2553,2022,100,2,1,7,4,NaN,NaN,1
171,68,2023,0,3,1,3,4,8,6,0
172,1441,2023,0,2,1,5,4,8,6,1
173,2402,2022,0,3,1,5,4,8,6,1
174,3337,2022,100,3,1,5,4,8,6,1
175,480,2023,0,2,1,13,4,8,6,1
176,1560,2023,0,3,1,16,4,8,6,1
177,1807,2023,100,3,1,7,4,8,6,1
178,3319,2022,0,3,1,10,4,8,6,0
179,2480,2022,0,3,1,10,4,8,6,1
180,2727,2022,100,3,1,9,4,8,6,1
181,2133,2022,100,3,1,7,4,8,6,1
182,3452,2022,100,3,1,NaN,0,0,0,1
183,355,2023,0,3,1,10,4,8,6,1
184,3043,2022,0,2,1,7,4,8,6,1
185,1857,2022,100,2,1,10,1,3,3,1
186,800,2023,100,3,1,6,4,8,6,1
187,3597,2021,0,2,1,7,NaN,NaN,NaN,1
188,1167,2023,0,3,1,NaN,4,8,6,1
189,302,2023,100,3,1,10,4,8,6,1
190,3242,2022,0,2,1,7,2,4,4,1
191,2820,2022,100,3,1,6,4,8,6,1
192,3726,2020,100,3,1,14,1,1,1,1
193,1039,2023,0,3,1,7,4,8,6,1
194,3641,2021,50,3,1,5,1,1,1,0
195,1257,2023,0,0,1,7,4,NaN,NaN,0
196,3054,2022,100,3,1,10,4,8,6,0
197,3443,2022,100,0,1,10,4,7,NaN,0
198,1527,2022,50,0,1,4,4,8,6,0
199,105,2023,0,3,1,7,4,8,6,1
200,1828,2022,0,3,1,NaN,4,8,6,1
201,2050,2022,0,3,1,10,4,8,6,1
202,3387,2022,100,3,1,7,4,8,6,1
203,1169,2023,0,3,1,10,4,8,6,1
204,2872,2022,100,0,1,5,3,3,5,0
205,2298,2022,100,3,1,3,4,8,6,1
206,2946,2022,0,3,1,10,4,8,6,0
207,1247,2023,0,3,1,16,4,2,2,1
208,2521,2022,0,3,1,7,4,8,6,1
209,3338,2022,0,2,1,5,4,0,0,1
210,1746,2022,100,0,1,10,4,8,6,1
211,2981,2022,100,1,1,2,4,8,6,1
212,752,2023,100,0,1,5,4,8,6,1
213,989,2023,0,2,1,12,4,8,6,1
214,1429,2023,100,3,1,10,4,8,6,1
215,2999,2022,100,3,1,7,4,8,6,1
216,3480,2021,0,0,1,10,4,8,6,2
217,3075,2022,100,2,0,NaN,3,6,5,2
218,1583,2023,100,3,1,5,4,8,6,1
219,3563,2021,100,3,1,NaN,1,5,NaN,0
220,288,2023,0,3,1,10,4,8,6,1
221,1804,2023,100,3,1,6,4,8,6,1
222,1122,2023,100,2,1,NaN,4,8,6,1
223,2409,2022,100,3,1,10,4,8,6,1
224,2989,2022,100,3,1,7,4,8,6,1
225,323,2022,0,3,1,0,4,0,0,2
226,616,2023,0,0,1,7,4,8,6,1
227,2291,2022,0,3,1,10,4,8,6,1
228,3659,2020,0,2,1,10,3,6,5,0
229,31,2023,0,3,1,7,4,8,6,1
230,1292,2023,100,3,1,10,4,8,6,1
231,3109,2022,100,3,1,10,4,8,6,0
232,1156,2023,100,3,1,5,4,8,6,1
233,459,2023,100,3,1,7,4,8,6,1
234,1706,2023,0,3,1,16,4,8,6,1
235,2718,2022,0,3,1,10,4,8,6,0
236,883,2023,0,3,1,5,4,8,6,1
237,469,2023,0,2,1,7,4,8,6,1
238,1158,2023,0,3,1,10,4,8,6,1
239,3126,2022,100,2,1,1,4,8,6,1
240,2980,2022,100,1,1,2,4,8,6,1
241,888,2023,100,2,1,10,4,8,6,1
242,3323,2022,100,3,1,7,4,8,6,1
243,3372,2022,0,3,1,5,4,8,6,1
244,2144,2022,100,3,1,10,4,8,6,1
245,595,2023,100,2,1,7,4,8,6,1
246,1800,2023,100,2,1,12,2,4,4,1
247,2447,2022,0,1,1,NaN,4,8,6,1
248,356,2023,100,3,1,10,4,8,6,1
249,3248,2022,0,3,1,7,4,8,6,1
250,1974,2022,100,3,1,5,4,8,6,1
251,3284,2022,100,3,1,10,4,8,6,1
252,1827,2022,0,3,1,10,4,8,6,1
253,2902,2022,100,3,1,7,2,4,4,1
254,3318,2022,0,3,1,10,4,8,6,0
255,1490,2023,100,3,1,5,4,8,6,1
256,221,2023,0,3,1,5,4,8,6,1
257,44,2023,0,3,1,7,4,8,6,1
258,211,2023,0,3,1,12,4,8,6,1
259,1147,2023,0,2,1,5,4,8,6,1
260,902,2023,0,3,1,10,4,8,6,1
261,2892,2022,100,2,1,7,1,2,2,1
262,263,2023,0,3,1,5,4,8,6,1
263,2991,2022,100,3,1,12,4,8,6,1
264,3344,2022,100,3,1,7,4,8,6,1
265,2695,2022,100,3,1,7,4,8,6,1
266,1883,2022,0,2,1,10,4,8,6,1
267,3013,2022,0,3,1,12,4,8,6,1
268,1764,2023,0,3,1,12,4,8,6,1
269,1065,2023,100,3,1,5,4,8,6,1
270,1356,2023,0,3,1,7,4,8,6,1
271,3382,2022,100,3,1,10,4,8,6,1
272,2281,2022,0,3,1,9,4,8,6,1
273,2349,2022,0,0,1,7,4,8,6,1
274,3351,2022,0,2,1,7,4,8,6,1
275,1364,2023,0,3,1,11,4,8,6,1
276,3649,2021,50,3,1,9,3,6,6,0
277,134,2023,0,3,1,12,4,8,6,0
278,699,2023,0,2,1,10,4,8,6,1
279,2691,2022,100,2,1,2,4,8,6,1
280,2730,2022,100,3,1,7,4,8,6,1
281,69,2023,0,3,1,3,4,8,6,0
282,1551,2023,0,3,1,10,4,8,6,1
283,3591,2021,100,0,1,10,4,8,6,2
284,3298,2022,100,3,1,5,4,8,6,1
285,138,2023,0,0,1,7,4,8,6,1
286,2906,2022,0,3,1,10,4,8,6,1
287,1661,2023,0,2,1,7,4,8,6,1
288,2361,2022,0,3,1,7,4,8,6,1
289,3720,2021,0,2,1,NaN,4,NaN,NaN,2
290,2647,2022,0,2,1,8,4,8,6,1
291,3492,2021,100,0,1,12,4,6,5,2
292,1275,2023,0,2,1,5,4,8,6,1
293,903,2023,0,3,1,10,4,8,6,1
294,3415,2022,100,3,1,10,4,8,6,1
295,2941,2022,0,3,1,10,4,8,6,1
296,2731,2022,100,3,1,12,4,8,6,1
297,2637,2022,100,2,1,11,4,8,6,0
298,1289,2023,0,3,1,5,4,8,6,1
299,1784,2023,0,3,1,6,4,8,6,1
300,647,2023,0,3,1,5,4,8,6,1
301,1524,2023,0,2,1,5,4,8,6,1
302,2271,2022,0,3,1,7,4,8,6,1
303,3517,2020,100,3,1,10,1,5,6,0
304,2110,2022,100,3,1,7,4,8,6,1
305,2959,2022,0,3,1,2,4,8,6,1
306,892,2023,0,3,1,7,4,8,6,1
307,1171,2023,0,3,1,7,4,8,6,1
308,2315,2022,100,2,1,7,4,8,6,1
309,1048,2023,0,2,1,NaN,2,4,4,1
310,3334,2022,100,3,1,7,4,8,6,1
311,3551,2021,100,3,1,NaN,1,1,1,0
312,1525,2023,0,3,1,11,4,8,6,1
313,956,2023,0,3,1,16,4,8,6,1
314,723,2023,0,3,1,5,4,8,6,1
315,338,2023,100,3,1,5,4,0,0,1
316,3332,2022,100,3,1,5,4,8,6,1
317,2432,2022,0,3,1,7,4,8,6,1
318,2802,2022,100,3,1,7,4,8,6,1
319,1212,2023,0,3,1,7,4,8,6,1
320,1555,2023,0,3,1,7,4,8,6,0
321,1958,2022,0,3,1,7,4,8,6,1
322,328,2023,0,3,1,6,4,8,6,1
323,290,2023,100,3,1,10,4,8,6,1
324,2080,2022,100,3,1,7,4,8,6,1
325,2151,2022,0,2,1,10,1,1,1,1
326,2085,2022,100,3,1,5,4,8,6,1
327,2100,2022,0,3,1,7,4,8,6,1
328,3297,2022,100,2,1,5,4,8,6,1
329,314,2023,0,3,1,10,4,8,6,1
330,3249,2022,0,3,1,7,4,8,6,1
331,3350,2022,0,2,1,7,4,8,6,1
332,3166,2022,100,3,1,10,4,8,6,0
333,1012,2023,0,3,1,10,4,8,6,1
334,342,2023,0,3,1,12,4,8,6,1
335,2573,2022,50,0,1,10,2,4,4,0
336,3383,2022,100,3,1,10,4,8,6,1
337,1472,2023,100,3,1,2,4,8,6,1
338,779,2023,100,3,1,11,4,0,0,1
339,1308,2023,100,2,1,12,4,NaN,NaN,2
340,1184,2023,0,3,1,5,4,8,6,1
341,1529,2023,0,3,1,7,4,8,6,1
342,1131,2023,0,3,1,9,4,8,6,1
343,672,2023,0,3,1,15,4,8,6,1
344,2766,2022,100,3,1,10,4,8,6,1
345,3541,2021,100,1,1,NaN,1,NaN,NaN,0
346,3352,2022,100,3,1,7,4,8,6,1
347,3617,2020,0,2,1,10,1,1,1,0
348,3299,2022,100,3,1,5,4,8,6,1
349,2850,2022,100,2,1,5,4,8,6,1
350,1280,2023,0,0,1,5,4,8,6,1
351,408,2023,0,3,1,12,4,8,6,1
352,1237,2023,0,3,1,5,4,8,6,1
353,3107,2022,100,3,1,5,4,8,6,1
354,1223,2023,100,0,1,5,4,8,6,0
355,3336,2022,100,3,1,5,4,8,6,1
356,110,2023,0,3,1,7,4,8,6,1
357,792,2023,0,3,1,7,4,8,6,1
358,1657,2023,0,3,1,2,4,8,6,1
359,3656,2021,50,0,1,12,4,NaN,NaN,1
360,2600,2022,100,3,1,10,4,8,6,1
361,652,2023,0,3,1,5,4,8,6,1
362,1055,2023,0,3,1,9,4,8,6,1
363,977,2023,100,3,1,5,4,8,6,1
364,411,2023,0,1,1,6,4,8,6,1
365,1912,2022,100,2,1,5,4,8,6,1
366,1988,2022,0,3,1,7,4,8,6,1
367,291,2023,100,3,1,10,4,8,6,1
368,309,2023,100,3,1,5,4,8,6,1
369,2450,2022,100,0,1,7,2,4,4,1
370,3406,2022,100,2,1,10,4,8,6,1
371,2860,2022,100,3,1,7,4,8,6,1
372,2333,2022,0,3,1,12,4,8,6,1
373,1063,2023,0,3,1,NaN,4,8,6,1
374,3536,2021,100,0,NaN,1,4,NaN,6,1
375,1381,2023,0,3,1,12,4,8,6,1

The auto generation is... alright. But doing it ourselves makes more interpretable sense.  

Let's test the results. To do so, we need to format the test dataset in the way of our train dataset.

In [32]:
data = pd.read_csv("ml_testset.csv")
data = data.drop(["Unnamed: 0"], axis=1)
# AutoVis DQfix changes with the dataset...
# data.loc[:, ["job_title", "salary_currency", "employee_residence", "company_location"]] = fixdq.group_rare_categories(data[["job_title", "salary_currency", "employee_residence", "company_location"]])
data.loc[:, ['work_year', 'remote_ratio']] = data[['work_year', 'remote_ratio']].astype(str)
old_feats = ['work_year', 'experience_level', 'employment_type', 'job_title', 'salary_currency', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']

categorical_feats = ['employment_type', 'job_title', 'salary_currency', 'employee_residence', 'company_location']
ordinal_feats = ['work_year', 'experience_level', 'remote_ratio', 'company_size']
# don't work on the un-DQed categorical variables
data = pd.concat([data, pd.get_dummies(data[["employment_type"]])], axis=1)
data = data.drop(["employment_type"], axis=1) 
data["experience_level"] = pd.Categorical(data["experience_level"], ["EN", "MI", "SE", "EX"], ordered=True).codes
data["work_year"] = pd.Categorical(data["work_year"], ["2020", "2021", "2022", "2023"], ordered=True).codes
data["remote_ratio"] = pd.Categorical(data["remote_ratio"], ["0", "50", "100"], ordered=True).codes
data["company_size"] = pd.Categorical(data["company_size"], ["S", "M", "L"], ordered=True).codes

for col in rare_cats.columns:
    data.loc[~data[col].isin(rare_cats[col].unique()), col] = "Rare"

data = pd.concat([data, pd.get_dummies(data[rare_cats.columns])], axis=1)

for col in ['employment_type_CT', 'employment_type_FL', 'employment_type_FT', 'employment_type_PT']:
    data.loc[:, col] = False

data = data.drop(['job_title', 'salary_currency', 'employee_residence', 'company_location'], axis=1) 

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 39 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   work_year                            376 non-null    int8
 1   experience_level                     376 non-null    int8
 2   remote_ratio                         376 non-null    int8
 3   company_size                         376 non-null    int8
 4   employment_type_CT                   376 non-null    bool
 5   employment_type_FL                   376 non-null    bool
 6   employment_type_FT                   376 non-null    bool
 7   employment_type_PT                   376 non-null    bool
 8   job_title_Analytics Engineer         376 non-null    bool
 9   job_title_Applied Scientist          376 non-null    bool
 10  job_title_Data Analyst               376 non-null    bool
 11  job_title_Data Architect             376 non-null    bool
 12  job_title_Data Engineer              376 non-null    bool
 13  job_title_Data Science Manager       376 non-null    bool
 14  job_title_Data Scientist             376 non-null    bool
 15  job_title_Machine Learning Engineer  376 non-null    bool
 16  job_title_Rare                       376 non-null    bool
 17  job_title_Research Engineer          376 non-null    bool
 18  job_title_Research Scientist         376 non-null    bool
 19  salary_currency_EUR                  376 non-null    bool
 20  salary_currency_GBP                  376 non-null    bool
 21  salary_currency_INR                  376 non-null    bool
 22  salary_currency_Rare                 376 non-null    bool
 23  salary_currency_USD                  376 non-null    bool
 24  employee_residence_CA                376 non-null    bool
 25  employee_residence_DE                376 non-null    bool
 26  employee_residence_ES                376 non-null    bool
 27  employee_residence_FR                376 non-null    bool
 28  employee_residence_GB                376 non-null    bool
 29  employee_residence_IN                376 non-null    bool
 30  employee_residence_Rare              376 non-null    bool
 31  employee_residence_US                376 non-null    bool
 32  company_location_CA                  376 non-null    bool
 33  company_location_DE                  376 non-null    bool
 34  company_location_ES                  376 non-null    bool
 35  company_location_GB                  376 non-null    bool
 36  company_location_IN                  376 non-null    bool
 37  company_location_Rare                376 non-null    bool
 38  company_location_US                  376 non-null    bool
dtypes: bool(35), int8(4)
memory usage: 14.4 KB

In [33]:
ag_test_df = TabularDataset(data)

y_pred = predictor.predict(ag_test_df)
y_pred.head()

0     46398.234375
1    140073.046875
2     98379.929688
3    140073.046875
4    139096.359375
Name: salary_in_usd, dtype: float32

In [34]:
from sklearn.metrics import r2_score

In [36]:
y_true = pd.read_csv("ml_testlabel.csv")
mean_squared_error(y_true["salary_in_usd"], y_pred)

2323972096.0

## What does a baseline do

In [4]:
data = pd.read_csv("ml_trainset.csv")

data = data.drop(["Unnamed: 0"], axis=1)
rare_cats = fixdq.group_rare_categories(data[["job_title", "salary_currency", "employee_residence", "company_location"]])
data.loc[:, ["job_title", "salary_currency", "employee_residence", "company_location"]] = rare_cats
data.loc[:, ['work_year', 'remote_ratio']] = data[['work_year', 'remote_ratio']].astype(str)
old_feats = ['work_year', 'experience_level', 'employment_type', 'job_title', 'salary_currency', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']

categorical_feats = ['employment_type', 'job_title', 'salary_currency', 'employee_residence', 'company_location']
ordinal_feats = ['work_year', 'experience_level', 'remote_ratio', 'company_size']
data = pd.concat([data, pd.get_dummies(data[categorical_feats])], axis=1)
data = data.drop(categorical_feats, axis=1)
data["experience_level"] = pd.Categorical(data["experience_level"], ["EN", "MI", "SE", "EX"], ordered=True).codes
data["work_year"] = pd.Categorical(data["work_year"], ["2020", "2021", "2022", "2023"], ordered=True).codes
data["remote_ratio"] = pd.Categorical(data["remote_ratio"], ["0", "50", "100"], ordered=True).codes
data["company_size"] = pd.Categorical(data["company_size"], ["S", "M", "L"], ordered=True).codes
data.loc[:, "salary_in_usd"] = data["salary_in_usd"].clip(0, 295000)

X = data.drop("salary_in_usd", axis=1)
y = data["salary_in_usd"]

In [5]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score

model = XGBRegressor()

param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [2, 5, 10],
    "learning_rate": [1e-3, 1e-2, 1e-1]
}

grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    verbose=1,
    scoring="neg_mean_squared_error"
)

grid_search.fit(X, y)
grid_search.best_params_

Fitting 5 folds for each of 27 candidates, totalling 135 fits

{'learning_rate': 0.1, 'max_depth': 2, 'n_estimators': 100}

In [6]:
best_model = grid_search.best_estimator_

In [19]:
data = pd.read_csv("ml_testset.csv")
data = data.drop(["Unnamed: 0"], axis=1)
# AutoVis DQfix changes with the dataset...
# data.loc[:, ["job_title", "salary_currency", "employee_residence", "company_location"]] = fixdq.group_rare_categories(data[["job_title", "salary_currency", "employee_residence", "company_location"]])
data.loc[:, ['work_year', 'remote_ratio']] = data[['work_year', 'remote_ratio']].astype(str)
old_feats = ['work_year', 'experience_level', 'employment_type', 'job_title', 'salary_currency', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']

categorical_feats = ['employment_type', 'job_title', 'salary_currency', 'employee_residence', 'company_location']
ordinal_feats = ['work_year', 'experience_level', 'remote_ratio', 'company_size']
# don't work on the un-DQed categorical variables
data = pd.concat([data, pd.get_dummies(data[["employment_type"]])], axis=1)
data = data.drop(["employment_type"], axis=1) 
data["experience_level"] = pd.Categorical(data["experience_level"], ["EN", "MI", "SE", "EX"], ordered=True).codes
data["work_year"] = pd.Categorical(data["work_year"], ["2020", "2021", "2022", "2023"], ordered=True).codes
data["remote_ratio"] = pd.Categorical(data["remote_ratio"], ["0", "50", "100"], ordered=True).codes
data["company_size"] = pd.Categorical(data["company_size"], ["S", "M", "L"], ordered=True).codes

for col in rare_cats.columns:
    data.loc[~data[col].isin(rare_cats[col].unique()), col] = "Rare"

data = pd.concat([data, pd.get_dummies(data[rare_cats.columns])], axis=1)

for col in ['employment_type_CT', 'employment_type_FL', 'employment_type_FT', 'employment_type_PT']:
    data.loc[:, col] = False

data = data.drop(['job_title', 'salary_currency', 'employee_residence', 'company_location'], axis=1) 

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 39 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   work_year                            376 non-null    int8
 1   experience_level                     376 non-null    int8
 2   remote_ratio                         376 non-null    int8
 3   company_size                         376 non-null    int8
 4   employment_type_CT                   376 non-null    bool
 5   employment_type_FL                   376 non-null    bool
 6   employment_type_FT                   376 non-null    bool
 7   employment_type_PT                   376 non-null    bool
 8   job_title_Analytics Engineer         376 non-null    bool
 9   job_title_Applied Scientist          376 non-null    bool
 10  job_title_Data Analyst               376 non-null    bool
 11  job_title_Data Architect             376 non-null    bool
 12  job_title_Data Engineer              376 non-null    bool
 13  job_title_Data Science Manager       376 non-null    bool
 14  job_title_Data Scientist             376 non-null    bool
 15  job_title_Machine Learning Engineer  376 non-null    bool
 16  job_title_Rare                       376 non-null    bool
 17  job_title_Research Engineer          376 non-null    bool
 18  job_title_Research Scientist         376 non-null    bool
 19  salary_currency_EUR                  376 non-null    bool
 20  salary_currency_GBP                  376 non-null    bool
 21  salary_currency_INR                  376 non-null    bool
 22  salary_currency_Rare                 376 non-null    bool
 23  salary_currency_USD                  376 non-null    bool
 24  employee_residence_CA                376 non-null    bool
 25  employee_residence_DE                376 non-null    bool
 26  employee_residence_ES                376 non-null    bool
 27  employee_residence_FR                376 non-null    bool
 28  employee_residence_GB                376 non-null    bool
 29  employee_residence_IN                376 non-null    bool
 30  employee_residence_Rare              376 non-null    bool
 31  employee_residence_US                376 non-null    bool
 32  company_location_CA                  376 non-null    bool
 33  company_location_DE                  376 non-null    bool
 34  company_location_ES                  376 non-null    bool
 35  company_location_GB                  376 non-null    bool
 36  company_location_IN                  376 non-null    bool
 37  company_location_Rare                376 non-null    bool
 38  company_location_US                  376 non-null    bool
dtypes: bool(35), int8(4)
memory usage: 14.4 KB

In [21]:
y_pred = best_model.predict(data)

In [23]:
y_true = pd.read_csv("ml_testlabel.csv")
mean_squared_error(y_true["salary_in_usd"], y_pred)

2164775936.0

In [147]:
from sklearn.model_selection import StratifiedKFold
from xgboost import XGBRegressor
import np

skf = StratifiedKFold(n_splits=5)
best_mse = np.inf
for i, (train_idx, test_idx) in enumerate(skf.split(X, y)):
    X_train, X_val, y_train, y_val = X.iloc[train_idx], X.iloc[test_idx], y.iloc[train_idx], y.iloc[test_idx]
    model = XGBRegressor()